import { Card, StatusPill } from "@living-textbook/ui";
import type { TeacherDraftAcceptanceReadiness } from "@living-textbook/content-model";

export function TeacherDraftAcceptanceReadinessPanel({ readiness, errors = [] }: { readiness: TeacherDraftAcceptanceReadiness; errors?: string[] }) {
  return <Card>
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-[var(--tenant-muted)]">Acceptance and operations evidence</p><h2 className="mt-1 text-lg font-bold">Draft release readiness remains blocked</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--tenant-muted)]">This reconciles policy, retention, export, recovery, and activation evidence for the exact draft and release candidate. It is evidence only; it cannot accept terms or activate storage.</p></div><div className="flex flex-wrap gap-2"><StatusPill label={readiness.status} tone="warning" /><StatusPill label="Not accepted" tone="warning" /><StatusPill label="No activation" tone="warning" /></div></div>
    <dl className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Tenant" value={readiness.tenantId} /><Metric label="Draft" value={readiness.draftId} /><Metric label="Release" value={readiness.releaseCandidate} /><Metric label="Retention" value={readiness.retentionAccepted ? "Accepted" : "Not accepted"} /></dl>
    {errors.length > 0 ? <ul className="mt-5 grid gap-2 text-sm leading-6 text-[var(--tenant-muted)]">{errors.map((error, index) => <li key={`acceptance-readiness-error-${index}`} className="rounded-lg border border-[var(--tenant-border)] bg-[var(--tenant-primary-soft)] p-3">{error}</li>)}</ul> : null}
    <div className="mt-5 grid gap-4 lg:grid-cols-3"><List title="Evidence required" items={readiness.requiredEvidence} /><List title="Blocked actions" items={readiness.blockedActions} /><List title="Next steps" items={readiness.nextSteps} /></div>
    <section className="mt-5 rounded-lg border border-[var(--tenant-border)] bg-[var(--tenant-primary-soft)] p-4"><p className="text-xs font-semibold uppercase text-[var(--tenant-muted)]">Open blockers</p><ul className="mt-2 grid gap-2 text-sm leading-6 text-[var(--tenant-text)]">{readiness.blockers.map((blocker, index) => <li key={`acceptance-readiness-blocker-${index}`}>{blocker}</li>)}</ul></section>
  </Card>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-[var(--tenant-border)] bg-[var(--tenant-primary-soft)] p-3"><dt className="text-xs font-semibold uppercase text-[var(--tenant-muted)]">{label}</dt><dd className="mt-1 break-words text-sm font-bold text-[var(--tenant-text)]">{value}</dd></div>; }
function List({ title, items }: { title: string; items: string[] }) { return <section className="rounded-lg border border-[var(--tenant-border)] bg-[var(--tenant-primary-soft)] p-4"><h3 className="text-sm font-bold text-[var(--tenant-text)]">{title}</h3><ul className="mt-3 grid gap-2 text-sm leading-6 text-[var(--tenant-muted)]">{items.map((item, index) => <li key={`${title}-${index}`}>{item}</li>)}</ul></section>; }
